export const libsIdName = {
	"10": "ABRERA.Josep Roca i Bros",
	"20": "AIGUAFREDA.Les Escoles Velles",
	"30": "ALELLA.Ferrer i Guàrdia",
	"40": "AMETLLA DEL V., L'.Josep Badia i Moret",
	"50": "ARENYS DE MAR.Pare Fidel Fita",
	"60": "ARENYS DE MUNT",
	"70": "ARTÉS",
	"80": "AVINYÓ",
	"90": "BADALONA.Can Casacuberta",
	"100": "BADALONA.Canyadó-Casagemes",
	"110": "BADALONA.Llefià Xavier Soto",
	"120": "BADALONA.Lloreda",
	"130": "BADALONA.Pomar",
	"140": "BADALONA.St. Roc",
	"150": "BADIA DEL V.Vicente Aleixandre",
	"160": "BALSARENY.Pere Casaldàliga",
	"170": "BARBERÀ DEL V.Esteve Paluzie",
	"180": "BCN CV.Barceloneta La Fraternitat",
	"190": "BCN CV.Francesca Bonnemaison",
	"200": "BCN CV.Gòtic Andreu Nin",
	"210": "BCN CV.Sant Pau - Santa Creu",
	"220": "BCN EIX.Esquerra Eixample-A. Centelles",
	"230": "BCN EIX.Fort Pienc",
	"240": "BCN EIX.Joan Miró",
	"250": "BCN EIX.Sagrada Família",
	"260": "BCN EIX.Sant Antoni Joan Oliver",
	"270": "BCN EIX.Sofia Barat",
	"280": "BCN GRA.Jaume Fuster",
	"290": "BCN GRA.Vallcarca Penitents - M. Antonieta Cot",
	"300": "BCN GRA.Vila de Gràcia",
	"310": "BCN HG.El Carmel Juan Marsé",
	"320": "BCN HG.Guinardó M. Rodoreda",
	"330": "BCN HG.Horta Can Mariner",
	"340": "BCN HG.Montbau Albert P. Baró",
	"350": "BCN LC.Les Corts Miquel Llongueras",
	"360": "BCN LC.Montserrat Abelló",
	"370": "BCN NB.Canyelles",
	"380": "BCN NB.Les Roquetes-Rafa Juncadella",
	"390": "BCN NB.Nou Barris",
	"400": "BCN NB.Vilapicina i la Torre Llobeta",
	"410": "BCN NB.Zona Nord",
	"420": "BCN SA.Bon Pastor",
	"430": "BCN SA.Ignasi Iglésias Can Fabra",
	"440": "BCN SA.La Sagrera - Marina Clotet",
	"450": "BCN SA.Trinitat Vella-J.Barbero",
	"460": "BCN SM.Francesc Candel",
	"470": "BCN SM.Poble-sec - Francesc Boix",
	"480": "BCN SM.Vapor Vell",
	"490": "BCN SMA.Camp de l'Arpa-Caterina Albert",
	"500": "BCN SMA.El Clot - Josep Benet",
	"510": "BCN SMA.Gabriel García Márquez",
	"520": "BCN SMA.Poblenou Manuel Arranz",
	"530": "BCN SMA.Ramon d'Alòs-Moner",
	"540": "BCN SMA.Xavier Benguerel",
	"550": "BCN SSG.Clarà",
	"560": "BCN SSG.Collserola Josep Miracle",
	"570": "BCN SSG.J.V. Foix",
	"580": "BCN SSG.St.Gervasi J.Maragall",
	"590": "BEGUES",
	"600": "BERGA.Ramon Vinyes i Cluet",
	"610": "Bibliobús Cavall Bernat",
	"620": "Bibliobús El Castellot",
	"630": "Bibliobús Guilleries",
	"640": "Bibliobús La Mola",
	"650": "Bibliobús Montau",
	"660": "Bibliobús Montnegre",
	"670": "Bibliobús Montserrat",
	"680": "Bibliobús Pedraforca",
	"690": "Bibliobús Puigdon",
	"700": "Bibliobús Serra de Bellmunt",
	"710": "Bibliobús Serra de Rubió",
	"720": "Bibliobús Serra del Cadí",
	"730": "Bibliobús Tagamanent",
	"740": "BIGUES I RIELLS DEL FAI",
	"750": "BRUC, EL.Verge de M",
	"760": "CABRERA DE MAR.Ilturo",
	"770": "CABRILS",
	"780": "CALDES D'ESTRAC.Can Milans",
	"790": "CALDES DE MONTBUI",
	"800": "CALELLA.Can Salvador de la Plaça",
	"810": "CANET DE MAR.P. Gual i Pujadas",
	"820": "CANOVELLES.Frederica Montseny",
	"830": "CAPELLADES.El Safareig",
	"840": "CARDEDEU.Marc de Vilalba",
	"850": "CARDONA.Marc de Cardona",
	"860": "CASTELLAR DEL V.Antoni Tort",
	"870": "CASTELLBISBAL.Josep Mateu i M.",
	"880": "CASTELLDEFELS",
	"890": "CERDANYOLA DEL V.Central",
	"900": "CERVELLÓ",
	"910": "COLLBATÓ.S.Durfort",
	"920": "CORBERA DE LLOB",
	"930": "CORNELLÀ DE LLOB.C.Campoamor",
	"940": "CORNELLÀ DE LLOB.Central",
	"950": "CORNELLÀ DE LLOB.Marta Mata",
	"960": "CORNELLÀ DE LLOB.St.Ildefons",
	"970": "CORNELLÀ DE LLOB.T.Pàmies",
	"980": "CUBELLES.Mn. Joan Avinyó",
	"990": "ESPARREGUERA.L'Ateneu",
	"1000": "ESPLUGUES DE LLOB.Pare Miquel d'Esplugues",
	"1010": "FRANQUESES DEL V., LES.Bellavista",
	"1020": "FRANQUESES DEL V., LES.C.d Avall",
	"1030": "GARRIGA, LA",
	"1040": "GAVÀ.Josep Soler Vidal",
	"1050": "GAVÀ.Marian Colomé",
	"1060": "GIRONELLA",
	"1070": "GRANOLLERS.Can Pedrals",
	"1080": "GRANOLLERS.Roca Umbert",
	"1090": "HOSPITALET DE LLOB.Bellvitge",
	"1100": "HOSPITALET DE LLOB.Can Sumarro",
	"1110": "HOSPITALET DE LLOB.J. Janés",
	"1120": "HOSPITALET DE LLOB.La Bòbila",
	"1130": "HOSPITALET DE LLOB.La Florida",
	"1140": "HOSPITALET DE LLOB.Plaça d'Europa",
	"1150": "HOSPITALET DE LLOB.Tecla Sala",
	"1160": "IGUALADA.Central",
	"1170": "LLAGOSTA, LA",
	"1180": "LLIÇÀ D'AMUNT",
	"1190": "LLINARS DEL V",
	"1200": "MALGRAT DE MAR.La Cooperativa",
	"1210": "MANLLEU",
	"1220": "MANRESA.Ateneu Les Bases",
	"1230": "MANRESA.C.",
	"1240": "MARTORELL.Francesc Pujols",
	"1250": "MARTORELLES.Lolita Milà",
	"1260": "MASNOU, EL.Joan Coromines",
	"1270": "MASQUEFA",
	"1280": "MATADEPERA.Àngel Guimerà",
	"1290": "MATARÓ.Antoni Comas",
	"1300": "MATARÓ.Pompeu Fabra",
	"1310": "MATARÓ.Popular",
	"1320": "MOIÀ.Biblioteca 1 d’octubre",
	"1330": "MOLINS DE REI.El Molí",
	"1340": "MOLLET DEL V.Can Mulà.J.Solé Tura",
	"1350": "MONTCADA I REIXAC.Can St. Joan",
	"1360": "MONTCADA I REIXAC.Elisenda de Montcada",
	"1370": "MONTGAT.Tirant lo Blanc",
	"1380": "MONTMELÓ.La Grua",
	"1390": "MONTORNÈS DEL V.R.Leveroni",
	"1400": "NAVARCLES.St. Valentí",
	"1410": "NAVÀS.Josep Mas Carreras",
	"1420": "ODENA.L'Atzavara",
	"1430": "OLESA DE M.Sta. Oliva",
	"1440": "PALAFOLLS.Enric Miralles",
	"1450": "PALAU-SOLITÀ I PLEGAMANS.L'Alzina",
	"1460": "PALLEJÀ",
	"1470": "PAPIOL,EL.",
	"1480": "PARETS DEL V.Can Rajoler",
	"1490": "PIERA",
	"1500": "PINEDA DE MAR.Manuel Serra i Moret",
	"1510": "PINEDA DE MAR.Poblenou",
	"1520": "POLINYÀ.Neus Català",
	"1530": "PONT DE VILOMARA, EL.",
	"1540": "PRAT DE LLOB., EL.Antonio Martín S.",
	"1550": "PREMIÀ DE DALT.Jaume Perich",
	"1560": "PREMIÀ DE MAR.M. Rosselló",
	"1570": "PUIG-REIG",
	"1580": "RIPOLLET",
	"1590": "ROCA DEL V., LA",
	"1600": "RODA DE TER.Bac de Roda",
	"1610": "RUBÍ.Mestre Martí Tauler",
	"1620": "SABADELL.Can Puiggener",
	"1630": "SABADELL.Els Safareigs",
	"1640": "SABADELL.La Serra",
	"1650": "SABADELL.Nord",
	"1660": "SABADELL.Ponent",
	"1670": "SABADELL.Sud",
	"1680": "SABADELL.Vapor Badia",
	"1690": "SALLENT.St. Antoni M. Claret",
	"1700": "SANTPEDOR.Pare Ignasi Casanovas",
	"1710": "SENTMENAT.Frederic Alfonso i Orfila",
	"1720": "SITGES.Josep Roig i Raventós",
	"1730": "SITGES.Santiago Rusiñol",
	"1740": "ST. ADRIÀ DE B.Font de la Mina",
	"1750": "ST. ADRIÀ DE B.Sant Adrià",
	"1760": "ST. ANDREU DE LA BARCA.Aigüestoses",
	"1770": "ST. ANDREU DE LLAVANERES.Font i D.",
	"1780": "ST. ANTONI DE V.Joana Raspall i J.",
	"1790": "ST. BOI DE LLOB.J. Rubió i Balaguer",
	"1800": "ST. BOI DE LLOB.Maria Aurèlia Capmany",
	"1810": "ST. CELONI.l'Escorxador",
	"1820": "ST. CLIMENT DE L.",
	"1830": "ST. CUGAT DEL V.Gabriel Ferrater",
	"1840": "ST. CUGAT DEL V.Marta Pessarrodona",
	"1850": "ST. CUGAT DEL V.Miquel Batllori",
	"1860": "ST. ESTEVE S.Joan Pomar i Solà",
	"1870": "ST. FELIU DE CODINES.Joan Petit i Aguilar",
	"1880": "ST. FELIU DE LLOB.Montserrat Roig",
	"1890": "ST. FELIU SASSERRA.St. Pere Almató",
	"1900": "ST. FOST DE CAMPSENTELLES",
	"1910": "ST. FRUITÓS DE B.Biblioteca",
	"1920": "ST. HIPÒLIT.Marquès de Remisa",
	"1930": "ST. JOAN DE VILATORRADA.Cal Gallifa",
	"1940": "ST. JOAN DESPÍ.M. Martí i Pol",
	"1950": "ST. JOAN DESPÍ.M.Rodoreda",
	"1960": "ST. JULIÀ DE V.Anton Carrera",
	"1970": "ST. JUST DESVERN.Joan Margarit",
	"1980": "ST. MARTÍ SARROCA. Neus Català i Pallejà",
	"1990": "ST. PERE DE RIBES.Josep Pla",
	"2000": "ST. PERE DE RIBES.Manuel de Pedrolo",
	"2010": "ST. PERE DE RIUDEBITLLES",
	"2020": "ST. PERE DE TORELLÓ.l'Esqueller",
	"2030": "ST. POL DE MAR",
	"2040": "ST. QUINTÍ DE M.J. Sardà",
	"2050": "ST. QUIRZE DE BESORA.Pompeu Fabra",
	"2060": "ST. QUIRZE DEL V. Marcel Ayats",
	"2070": "ST. SADURNÍ.Ramon Bosch de Noya",
	"2080": "ST. VICENÇ DE C.S. Vives Casajuana",
	"2090": "ST. VICENÇ DE MONTALT.La Muntala",
	"2100": "ST. VICENÇ DELS HORTS.Les Voltes",
	"2110": "STA. COLOMA DE C.Pilarín Bayés",
	"2120": "STA. COLOMA DE GRAMENET.Can Peixauet",
	"2130": "STA. COLOMA DE GRAMENET.Central",
	"2140": "STA. COLOMA DE GRAMENET.Fondo",
	"2150": "STA. COLOMA DE GRAMENET.Singuerlín",
	"2160": "STA. EULÀLIA DE RONÇANA",
	"2170": "STA. M.MONJOS",
	"2180": "STA. MARGARIDA DE MONTBUI",
	"2190": "STA. MARIA DE ,TORDERA.Ferran Soldevila",
	"2200": "STA. MARIA DE PALAUTORDERA.Ferran Soldevila",
	"2210": "STA. PERPÈTUA DE MOGODA",
	"2220": "STA. SUSANNA",
	"2230": "SÚRIA",
	"2240": "TARADELL.Antoni Pladevall i Font",
	"2250": "TEIÀ.Can Llaurador",
	"2260": "TERRASSA.Central de Terrassa",
	"2270": "TERRASSA.Districte 2",
	"2280": "TERRASSA.Districte 3",
	"2290": "TERRASSA.Districte 4",
	"2300": "TERRASSA.Districte 5",
	"2310": "TERRASSA.Districte 6",
	"2320": "TIANA.Can Baratau",
	"2330": "TONA.Caterina Figueras",
	"2340": "TORDERA",
	"2350": "TORELLÓ.Barri Montserrat",
	"2360": "TORELLÓ.Dos Rius",
	"2370": "TORRELLES DE LLOB.Pompeu Fabra",
	"2380": "VACARISSES.El Castell",
	"2390": "VALLIRANA.J.M. López-Picó",
	"2400": "VIC.Pilarin Bayés",
	"2410": "VILADECANS",
	"2420": "VILADECAVALLS.Pere Calders",
	"2430": "VILAFRANCA DEL P.Torras i Bages",
	"2440": "VILANOVA DEL CAMÍ",
	"2450": "VILANOVA DEL VALLÈS",
	"2460": "VILANOVA I LA G.Armand Cardona Torrandell",
	"2470": "VILANOVA I LA G.Joan Oliva i Milà",
	"2480": "VILASSAR DE DALT.Can Manyer",
	"2490": "VILASSAR DE MAR.Ernest Lluch"
}