export const libsNameId: { [key: string]: string } = {
	"ABRERA.Josep Roca i Bros": "10",
	"AIGUAFREDA.Les Escoles Velles": "20",
	"ALELLA.Ferrer i Guàrdia": "30",
	"AMETLLA DEL V., L'.Josep Badia i Moret": "40",
	"ARENYS DE MAR.Pare Fidel Fita": "50",
	"ARENYS DE MUNT": "60",
	"ARTÉS": "70",
	"AVINYÓ": "80",
	"BADALONA.Can Casacuberta": "90",
	"BADALONA.Canyadó-Casagemes": "100",
	"BADALONA.Llefià Xavier Soto": "110",
	"BADALONA.Lloreda": "120",
	"BADALONA.Pomar": "130",
	"BADALONA.St. Roc": "140",
	"BADIA DEL V.Vicente Aleixandre": "150",
	"BALSARENY.Pere Casaldàliga": "160",
	"BARBERÀ DEL V.Esteve Paluzie": "170",
	"BCN CV.Barceloneta La Fraternitat": "180",
	"BCN CV.Francesca Bonnemaison": "190",
	"BCN CV.Gòtic Andreu Nin": "200",
	"BCN CV.Sant Pau - Santa Creu": "210",
	"BCN EIX.Esquerra Eixample-A. Centelles": "220",
	"BCN EIX.Fort Pienc": "230",
	"BCN EIX.Joan Miró": "240",
	"BCN EIX.Sagrada Família": "250",
	"BCN EIX.Sant Antoni Joan Oliver": "260",
	"BCN EIX.Sofia Barat": "270",
	"BCN GRA.Jaume Fuster": "280",
	"BCN GRA.Vallcarca Penitents - M. Antonieta Cot": "290",
	"BCN GRA.Vila de Gràcia": "300",
	"BCN HG.El Carmel Juan Marsé": "310",
	"BCN HG.Guinardó M. Rodoreda": "320",
	"BCN HG.Horta Can Mariner": "330",
	"BCN HG.Montbau Albert P. Baró": "340",
	"BCN LC.Les Corts Miquel Llongueras": "350",
	"BCN LC.Montserrat Abelló": "360",
	"BCN NB.Canyelles": "370",
	"BCN NB.Les Roquetes-Rafa Juncadella": "380",
	"BCN NB.Nou Barris": "390",
	"BCN NB.Vilapicina i la Torre Llobeta": "400",
	"BCN NB.Zona Nord": "410",
	"BCN SA.Bon Pastor": "420",
	"BCN SA.Ignasi Iglésias Can Fabra": "430",
	"BCN SA.La Sagrera - Marina Clotet": "440",
	"BCN SA.Trinitat Vella-J.Barbero": "450",
	"BCN SM.Francesc Candel": "460",
	"BCN SM.Poble-sec - Francesc Boix": "470",
	"BCN SM.Vapor Vell": "480",
	"BCN SMA.Camp de l'Arpa-Caterina Albert": "490",
	"BCN SMA.El Clot - Josep Benet": "500",
	"BCN SMA.Gabriel García Márquez": "510",
	"BCN SMA.Poblenou Manuel Arranz": "520",
	"BCN SMA.Ramon d'Alòs-Moner": "530",
	"BCN SMA.Xavier Benguerel": "540",
	"BCN SSG.Clarà": "550",
	"BCN SSG.Collserola Josep Miracle": "560",
	"BCN SSG.J.V. Foix": "570",
	"BCN SSG.St.Gervasi J.Maragall": "580",
	"BEGUES": "590",
	"BERGA.Ramon Vinyes i Cluet": "600",
	"Bibliobús Cavall Bernat": "610",
	"Bibliobús El Castellot": "620",
	"Bibliobús Guilleries": "630",
	"Bibliobús La Mola": "640",
	"Bibliobús Montau": "650",
	"Bibliobús Montnegre": "660",
	"Bibliobús Montserrat": "670",
	"Bibliobús Pedraforca": "680",
	"Bibliobús Puigdon": "690",
	"Bibliobús Serra de Bellmunt": "700",
	"Bibliobús Serra de Rubió": "710",
	"Bibliobús Serra del Cadí": "720",
	"Bibliobús Tagamanent": "730",
	"BIGUES I RIELLS DEL FAI": "740",
	"BRUC, EL.Verge de M": "750",
	"CABRERA DE MAR.Ilturo": "760",
	"CABRILS": "770",
	"CALDES D'ESTRAC.Can Milans": "780",
	"CALDES DE MONTBUI": "790",
	"CALELLA.Can Salvador de la Plaça": "800",
	"CANET DE MAR.P. Gual i Pujadas": "810",
	"CANOVELLES.Frederica Montseny": "820",
	"CAPELLADES.El Safareig": "830",
	"CARDEDEU.Marc de Vilalba": "840",
	"CARDONA.Marc de Cardona": "850",
	"CASTELLAR DEL V.Antoni Tort": "860",
	"CASTELLBISBAL.Josep Mateu i M.": "870",
	"CASTELLDEFELS": "880",
	"CERDANYOLA DEL V.Central": "890",
	"CERVELLÓ": "900",
	"COLLBATÓ.S.Durfort": "910",
	"CORBERA DE LLOB": "920",
	"CORNELLÀ DE LLOB.C.Campoamor": "930",
	"CORNELLÀ DE LLOB.Central": "940",
	"CORNELLÀ DE LLOB.Marta Mata": "950",
	"CORNELLÀ DE LLOB.St.Ildefons": "960",
	"CORNELLÀ DE LLOB.T.Pàmies": "970",
	"CUBELLES.Mn. Joan Avinyó": "980",
	"ESPARREGUERA.L'Ateneu": "990",
	"ESPLUGUES DE LLOB.Pare Miquel d'Esplugues": "1000",
	"FRANQUESES DEL V., LES.Bellavista": "1010",
	"FRANQUESES DEL V., LES.C.d Avall": "1020",
	"GARRIGA, LA": "1030",
	"GAVÀ.Josep Soler Vidal": "1040",
	"GAVÀ.Marian Colomé": "1050",
	"GIRONELLA": "1060",
	"GRANOLLERS.Can Pedrals": "1070",
	"GRANOLLERS.Roca Umbert": "1080",
	"HOSPITALET DE LLOB.Bellvitge": "1090",
	"HOSPITALET DE LLOB.Can Sumarro": "1100",
	"HOSPITALET DE LLOB.J. Janés": "1110",
	"HOSPITALET DE LLOB.La Bòbila": "1120",
	"HOSPITALET DE LLOB.La Florida": "1130",
	"HOSPITALET DE LLOB.Plaça d'Europa": "1140",
	"HOSPITALET DE LLOB.Tecla Sala": "1150",
	"IGUALADA.Central": "1160",
	"LLAGOSTA, LA": "1170",
	"LLIÇÀ D'AMUNT": "1180",
	"LLINARS DEL V": "1190",
	"MALGRAT DE MAR.La Cooperativa": "1200",
	"MANLLEU": "1210",
	"MANRESA.Ateneu Les Bases": "1220",
	"MANRESA.C.": "1230",
	"MARTORELL.Francesc Pujols": "1240",
	"MARTORELLES.Lolita Milà": "1250",
	"MASNOU, EL.Joan Coromines": "1260",
	"MASQUEFA": "1270",
	"MATADEPERA.Àngel Guimerà": "1280",
	"MATARÓ.Antoni Comas": "1290",
	"MATARÓ.Pompeu Fabra": "1300",
	"MATARÓ.Popular": "1310",
	"MOIÀ.Biblioteca 1 d’octubre": "1320",
	"MOLINS DE REI.El Molí": "1330",
	"MOLLET DEL V.Can Mulà.J.Solé Tura": "1340",
	"MONTCADA I REIXAC.Can St. Joan": "1350",
	"MONTCADA I REIXAC.Elisenda de Montcada": "1360",
	"MONTGAT.Tirant lo Blanc": "1370",
	"MONTMELÓ.La Grua": "1380",
	"MONTORNÈS DEL V.R.Leveroni": "1390",
	"NAVARCLES.St. Valentí": "1400",
	"NAVÀS.Josep Mas Carreras": "1410",
	"ODENA.L'Atzavara": "1420",
	"OLESA DE M.Sta. Oliva": "1430",
	"PALAFOLLS.Enric Miralles": "1440",
	"PALAU-SOLITÀ I PLEGAMANS.L'Alzina": "1450",
	"PALLEJÀ": "1460",
	"PAPIOL,EL.": "1470",
	"PARETS DEL V.Can Rajoler": "1480",
	"PIERA": "1490",
	"PINEDA DE MAR.Manuel Serra i Moret": "1500",
	"PINEDA DE MAR.Poblenou": "1510",
	"POLINYÀ.Neus Català": "1520",
	"PONT DE VILOMARA, EL.": "1530",
	"PRAT DE LLOB., EL.Antonio Martín S.": "1540",
	"PREMIÀ DE DALT.Jaume Perich": "1550",
	"PREMIÀ DE MAR.M. Rosselló": "1560",
	"PUIG-REIG": "1570",
	"RIPOLLET": "1580",
	"ROCA DEL V., LA": "1590",
	"RODA DE TER.Bac de Roda": "1600",
	"RUBÍ.Mestre Martí Tauler": "1610",
	"SABADELL.Can Puiggener": "1620",
	"SABADELL.Els Safareigs": "1630",
	"SABADELL.La Serra": "1640",
	"SABADELL.Nord": "1650",
	"SABADELL.Ponent": "1660",
	"SABADELL.Sud": "1670",
	"SABADELL.Vapor Badia": "1680",
	"SALLENT.St. Antoni M. Claret": "1690",
	"SANTPEDOR.Pare Ignasi Casanovas": "1700",
	"SENTMENAT.Frederic Alfonso i Orfila": "1710",
	"SITGES.Josep Roig i Raventós": "1720",
	"SITGES.Santiago Rusiñol": "1730",
	"ST. ADRIÀ DE B.Font de la Mina": "1740",
	"ST. ADRIÀ DE B.Sant Adrià": "1750",
	"ST. ANDREU DE LA BARCA.Aigüestoses": "1760",
	"ST. ANDREU DE LLAVANERES.Font i D.": "1770",
	"ST. ANTONI DE V.Joana Raspall i J.": "1780",
	"ST. BOI DE LLOB.J. Rubió i Balaguer": "1790",
	"ST. BOI DE LLOB.Maria Aurèlia Capmany": "1800",
	"ST. CELONI.l'Escorxador": "1810",
	"ST. CLIMENT DE L.": "1820",
	"ST. CUGAT DEL V.Gabriel Ferrater": "1830",
	"ST. CUGAT DEL V.Marta Pessarrodona": "1840",
	"ST. CUGAT DEL V.Miquel Batllori": "1850",
	"ST. ESTEVE S.Joan Pomar i Solà": "1860",
	"ST. FELIU DE CODINES.Joan Petit i Aguilar": "1870",
	"ST. FELIU DE LLOB.Montserrat Roig": "1880",
	"ST. FELIU SASSERRA.St. Pere Almató": "1890",
	"ST. FOST DE CAMPSENTELLES": "1900",
	"ST. FRUITÓS DE B.Biblioteca": "1910",
	"ST. HIPÒLIT.Marquès de Remisa": "1920",
	"ST. JOAN DE VILATORRADA.Cal Gallifa": "1930",
	"ST. JOAN DESPÍ.M. Martí i Pol": "1940",
	"ST. JOAN DESPÍ.M.Rodoreda": "1950",
	"ST. JULIÀ DE V.Anton Carrera": "1960",
	"ST. JUST DESVERN.Joan Margarit": "1970",
	"ST. MARTÍ SARROCA. Neus Català i Pallejà": "1980",
	"ST. PERE DE RIBES.Josep Pla": "1990",
	"ST. PERE DE RIBES.Manuel de Pedrolo": "2000",
	"ST. PERE DE RIUDEBITLLES": "2010",
	"ST. PERE DE TORELLÓ.l'Esqueller": "2020",
	"ST. POL DE MAR": "2030",
	"ST. QUINTÍ DE M.J. Sardà": "2040",
	"ST. QUIRZE DE BESORA.Pompeu Fabra": "2050",
	"ST. QUIRZE DEL V. Marcel Ayats": "2060",
	"ST. SADURNÍ.Ramon Bosch de Noya": "2070",
	"ST. VICENÇ DE C.S. Vives Casajuana": "2080",
	"ST. VICENÇ DE MONTALT.La Muntala": "2090",
	"ST. VICENÇ DELS HORTS.Les Voltes": "2100",
	"STA. COLOMA DE C.Pilarín Bayés": "2110",
	"STA. COLOMA DE GRAMENET.Can Peixauet": "2120",
	"STA. COLOMA DE GRAMENET.Central": "2130",
	"STA. COLOMA DE GRAMENET.Fondo": "2140",
	"STA. COLOMA DE GRAMENET.Singuerlín": "2150",
	"STA. EULÀLIA DE RONÇANA": "2160",
	"STA. M.MONJOS": "2170",
	"STA. MARGARIDA DE MONTBUI": "2180",
	"STA. MARIA DE ,TORDERA.Ferran Soldevila": "2190",
	"STA. MARIA DE PALAUTORDERA.Ferran Soldevila": "2200",
	"STA. PERPÈTUA DE MOGODA": "2210",
	"STA. SUSANNA": "2220",
	"SÚRIA": "2230",
	"TARADELL.Antoni Pladevall i Font": "2240",
	"TEIÀ.Can Llaurador": "2250",
	"TERRASSA.Central de Terrassa": "2260",
	"TERRASSA.Districte 2": "2270",
	"TERRASSA.Districte 3": "2280",
	"TERRASSA.Districte 4": "2290",
	"TERRASSA.Districte 5": "2300",
	"TERRASSA.Districte 6": "2310",
	"TIANA.Can Baratau": "2320",
	"TONA.Caterina Figueras": "2330",
	"TORDERA": "2340",
	"TORELLÓ.Barri Montserrat": "2350",
	"TORELLÓ.Dos Rius": "2360",
	"TORRELLES DE LLOB.Pompeu Fabra": "2370",
	"VACARISSES.El Castell": "2380",
	"VALLIRANA.J.M. López-Picó": "2390",
	"VIC.Pilarin Bayés": "2400",
	"VILADECANS": "2410",
	"VILADECAVALLS.Pere Calders": "2420",
	"VILAFRANCA DEL P.Torras i Bages": "2430",
	"VILANOVA DEL CAMÍ": "2440",
	"VILANOVA DEL VALLÈS": "2450",
	"VILANOVA I LA G.Armand Cardona Torrandell": "2460",
	"VILANOVA I LA G.Joan Oliva i Milà": "2470",
	"VILASSAR DE DALT.Can Manyer": "2480",
	"VILASSAR DE MAR.Ernest Lluch": "2490"
}